# Generated by Django 5.0.6 on 2024-07-03 23:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtotextrequest',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='speech_to_text'),
        ),
        migrations.AlterField(
            model_name='texttospeechrequest',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='text_to_speech'),
        ),
    ]
