# Generated by Django 5.0.6 on 2024-07-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_speechtotextrequest_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtotextrequest',
            name='audio_file',
            field=models.FileField(upload_to='speech_to_text'),
        ),
    ]
